### ISSUE TITLE
OSError: I2C bus error

### ISSUE THREAD

**Issue by BeginnerOnPy** [pycom/pycom-libraries#50]
Traceback (most recent call last):
  File "main.py", line 31, in <module>
  File "/flash/lib/pycoproc.py", line 249, in button_pressed
  File "/flash/lib/pycoproc.py", line 151, in peek_memory
  File "/flash/lib/pycoproc.py", line 116, in _write
  File "/flash/lib/pycoproc.py", line 130, in _wait
OSError: I2C bus error

**Comment by sdaniel55** [comment]
Hi @BeginnerOnPy, could you provide some example code? Thanks!

**Comment by fusspawn** [comment]
Closing this as nearly a year of inactivity. Please feel free to reopen if this still effects you :)
