### ISSUE TITLE
MQTT Client connect to Azure IoTHub "IndexError: bytes index out of range" error

### ISSUE THREAD

**Issue by Milan991** [pycom/pycom-libraries#93]
## What are the steps to reproduce this issue?
1. Connect to WiFi network
2. Call `MQTTClient(...)` with Azure IoTHub credentials.
3. Call `client.connect()`.

## What happens?
Following error appears:

> Traceback (most recent call last):
>   File "main.py", line 45, in <module>
>   File "/flash/lib/mqtt.py", line 85, in connect
> IndexError: bytes index out of range

## What were you expecting to happen?
I'm expecting successfully MQTT connect to Azure IoTHub. 

## What versions of software are you using?
(sysname='LoPy4', nodename='LoPy4', release='1.18.1.r7', version='v1.8.6-849-d1c5ea9 on 2018-12-17', machine='LoPy4 with ESP32', lorawan='1.0.2', sigfox='1.0.1')

**Comment by Milan991** [comment]
Any updates on this issue?
